packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    peerDependencies:
      typescript: ">=2.7"
  "@graphql-codegen/cli@1.21.4":
    peerDependencies:
      typescript: ">=2.7"
  graphql-config@3.2.0:
    peerDependencies:
      typescript: ">=2.7"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
