name: Semantic Release
on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - name: install deps
        run: bun install
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun run --bun semantic-release
  merge:
    needs: semantic-release
    runs-on: ubuntu-latest
    steps:
      - name: merge to develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
