name: GraphQL Schema Validation
on:
  pull_request:
    types: [edited, labeled, opened, synchronize, reopened]
jobs:
  graphql-inspector:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - uses: kamilkisiela/graphql-inspector@v2.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          endpoint: https://ericgraphql.dictybase.dev/graphql
