name: GraphQL Schema Validation
on:
  pull_request:
    types: [edited, labeled, opened, synchronize, reopened]
jobs:
  graphql-inspector:
    runs-on: ubuntu-20.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.15.0
      - name: check out code
        uses: actions/checkout@v2
      - name: download cli tool
        run: npm i -g graphql-schema-utilities
      - name: generate combined schema
        run: graphql-schema-utilities -s "*.graphql" -o "combined.graphql"
      - name: validate schema
        uses: kamilkisiela/graphql-inspector@v2.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: combined.graphql
